# .github/workflows/release-please.yaml
name: release-please

on:
    push:
        branches:
            - main

permissions: write-all
  # contents: write
  # pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ secrets.CREATE_APP_TOKEN_APP_ID }}
                private-key: ${{ secrets.CREATE_APP_TOKEN_PRIVATE_KEY }}
            - uses: googleapis/release-please-action@v4
              with:
                token: ${{ steps.app-token.outputs.token }}